//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string NormalizedUserName { get; set; }
        public string Email { get; set; }
        public string NormalizedEmail { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string ConcurrencyStamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTimeOffset> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string UserType { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentMiddleName { get; set; }
        public string StudentLastName { get; set; }
        public Nullable<System.DateTime> StudentDOB { get; set; }
        public string StudentBirthPlace { get; set; }
        public string StudentGender { get; set; }
        public string StudentBloodGroup { get; set; }
        public string StudentNationality { get; set; }
        public string StudentMotherTongue { get; set; }
        public string StudentCategory { get; set; }
        public string StudentReligion { get; set; }
        public string StudentCaste { get; set; }
        public string StudentAddress { get; set; }
        public string StudentLocality { get; set; }
        public string StudentPincode { get; set; }
        public string StudentCity { get; set; }
        public string StudentState { get; set; }
        public string StudentCountry { get; set; }
        public string StudentPhone { get; set; }
        public string StudentParentMobile { get; set; }
        public string StudentParentEmail { get; set; }
        public string StudentParentName { get; set; }
        public string StudentParentPhone { get; set; }
        public string StudentParentAddress { get; set; }
        public string StudentParentLocality { get; set; }
        public string StudentParentPincode { get; set; }
        public string StudentParentCity { get; set; }
        public string StudentParentState { get; set; }
        public string StudentParentCountry { get; set; }
        public string StudentParentRelation { get; set; }
        public string StudentParentEducation { get; set; }
        public string StudentParentOccupation { get; set; }
        public string StudentParentIncome { get; set; }
        public string StudentParentFamilyIncome { get; set; }
        public string StudentFatherName { get; set; }
        public string StudentFatherMobile { get; set; }
        public string StudentFatherJob { get; set; }
        public string StudentMotherName { get; set; }
        public string StudentMotherMobile { get; set; }
        public string StudentMotherJob { get; set; }
        public string StudentAadharNumber { get; set; }
        public string StudentPreviousSchoolName { get; set; }
        public string StudentPreviousSchoolDetails { get; set; }
        public string StudentPreviousQualification { get; set; }
        public string UserDepartment { get; set; }
        public string StudentLCNo { get; set; }
        public string StudentAdmissionNoGR { get; set; }
        public string UIDAdharCardNo { get; set; }
        public string GeneralRegisterNO { get; set; }
        public string StudentSubCaste { get; set; }
        public string StudentTaluka { get; set; }
        public string StudentDistrict { get; set; }
        public string DateOfBirthinwords { get; set; }
        public string SchoolUDISENo { get; set; }
        public string StudentProgress { get; set; }
        public string StudentConduct { get; set; }
        public Nullable<System.DateTime> DateOfLeavingSchool { get; set; }
        public string StandardInWhichStudyingFigure { get; set; }
        public string StandardInWhichStudyingWord { get; set; }
        public string ReasonForLeavingSchool { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> StudentAdmissionDates { get; set; }
        public string StudentStandard { get; set; }
        public string StandardInWhichStudyingSinceWhenFigure { get; set; }
        public string StandardInWhichStudyingSinceWhenWord { get; set; }
        public string StudentSARALID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateofAdmissionImport { get; set; }
        public string StandardDivisionImport { get; set; }
        public string Photo { get; set; }
        public string AdmissionUpdate { get; set; }
        public string GRType { get; set; }
        public string StandardFromLeft { get; set; }
        public string DivisionFromLeft { get; set; }
        public Nullable<System.DateTime> ReceivingDateLC { get; set; }
        public string OtherRemarks { get; set; }
        public string CorrectEntrySign { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public string StudentSteam { get; set; }
        public string AdmissionFormPhoto { get; set; }
        public string BirthLeavingCertificatePhoto { get; set; }
        public string CasteCertificatePhoto { get; set; }
        public string AdharCardPhoto { get; set; }
        public string FirstGuardianEmail { get; set; }
        public string SecondGuardianEmail { get; set; }
        public string FirstGuardianMobile { get; set; }
        public string SecondGuardianMobile { get; set; }
        public Nullable<int> Feeid { get; set; }
        public string ImportDate { get; set; }
        public string StudentBatch { get; set; }
    }
}
