//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTDailyUpdate
    {
        public int DTDailyUpdate1 { get; set; }
        public Nullable<int> DailyUpdateID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Subject { get; set; }
        public string ClassWork { get; set; }
        public string HomeAssignment { get; set; }
        public string AcadamicYear { get; set; }
    }
}
