//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MstVoucher
    {
        [Key]
        public int VoucherId { get; set; }
        public string VoucherName { get; set; }
        public string CreditDebit { get; set; }
        public string AcadamicYear { get; set; }
    }
}
