//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrimEngFee
    {        [Key]
        public int id { get; set; }
        public string Mediam { get; set; }
        public string FeeIDNo { get; set; }
        public string NameofStudent { get; set; }
        public string Standard2223 { get; set; }
        public string FEESRECEIVABLEFOR222023 { get; set; }
        public string NewAdmissionFees222023 { get; set; }
        public string FEESRECEIVEDONMANUALRECEIPTS222023 { get; set; }
        public string DiscountSuprimeCourt { get; set; }
        public string BALANCE222023 { get; set; }
        public string StandardRoman { get; set; }
        public string StudentBatch { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    }
}
