//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryBalancePending
    {
        [Key]        public string StandardRoman { get; set; }
        public string BALANCE222023 { get; set; }
        public string FeeIDNo { get; set; }
        public string NameofStudent { get; set; }
        public int id { get; set; }
        public Nullable<int> FeeStudentID { get; set; }
        public string FeeStudentName { get; set; }
        public string FeeBatchName { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public string FeeCourseName { get; set; }
        public string StudentBatch { get; set; }
    }
}
