//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryBookIssue
    {
        public int BookId { get; set; }
        public string BookDescription { get; set; }
        public int BookIssueId { get; set; }
        public string BookIssueType { get; set; }
        public string BookCourse { get; set; }
        public string BookBatch { get; set; }
        public string BookIssueStudent { get; set; }
        public Nullable<int> BookIssueStudentID { get; set; }
        public string BookIssueEmployee { get; set; }
        public Nullable<int> BookIssueEmployeeID { get; set; }
        public string BookIssueName { get; set; }
        public string BookIssueCode { get; set; }
        public Nullable<System.DateTime> BookIssueDate { get; set; }
        public Nullable<System.DateTime> BookDueDate { get; set; }
        public string AcadamicYear { get; set; }
        public string Status { get; set; }
        public string BookDescriptionIssue { get; set; }
        public Nullable<System.DateTime> BookReturnDate { get; set; }
    }
}
