//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryBook
    {        [Key]
        public int BookId { get; set; }
        public Nullable<System.DateTime> BookPurchaseDate { get; set; }
        public string BookISBNNo { get; set; }
        public string BookTitle { get; set; }
        public string BookEdition { get; set; }
        public string BookPublisher { get; set; }
        public string BookShelfNo { get; set; }
        public Nullable<decimal> BookCost { get; set; }
        public string BookCondition { get; set; }
        public string BookBillNo { get; set; }
        public string BookNo { get; set; }
        public string BookAuthor { get; set; }
        public string BookCategory { get; set; }
        public Nullable<int> BookNoCopies { get; set; }
        public string BookPosition { get; set; }
        public string BookLanguage { get; set; }
        public string Notes { get; set; }
        public string AcadamicYear { get; set; }
        public string BookDescription { get; set; }
    }
}
