//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryBookReturn
    {        [Key]
        public int BookId { get; set; }
        public string BookDescription { get; set; }
        public int BookReturnId { get; set; }
        public Nullable<int> BookReferenceID { get; set; }
        public string BookReturnTitle { get; set; }
        public string BookReturnAuthor { get; set; }
        public Nullable<System.DateTime> BookReturnDate { get; set; }
        public Nullable<decimal> BookReturnFineAmt { get; set; }
        public Nullable<int> BookReturnDelayDays { get; set; }
        public string BookReturnRemarks { get; set; }
        public string BookReturnType { get; set; }
        public Nullable<System.DateTime> BookRenewalDuedate { get; set; }
        public string BookReturnFrom { get; set; }
        public Nullable<int> BookIssueId { get; set; }
    }
}
