//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryClassTeacher
    {        [Key]
        public string CourseName { get; set; }
        public string CourseBatch { get; set; }
        public string TeacherEmpUserName { get; set; }
        public string AcadamicYear { get; set; }
        public string Qualification { get; set; }
        public string ExperianceDetails { get; set; }
        public string EName { get; set; }
    }
}
