//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryExamMarkObtainedNew
    {        [Key]
        public string TermName { get; set; }
        public Nullable<int> cnt { get; set; }
        public int ExamId { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
    }
}
