//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryFeeSubCategory
    {
        [Key]
        public int FeeSubCategoryId { get; set; }
        public string FeeCategoryName { get; set; }
        public string FeeSubCategoryName { get; set; }
        public Nullable<decimal> FeeSubCategoryAmount { get; set; }
        public string FeeType { get; set; }
        public string AcadamicYear { get; set; }
        public Nullable<System.DateTime> PaymentStartDate { get; set; }
        public Nullable<System.DateTime> PaymentEndDate { get; set; }
        public string FeeMedium { get; set; }
        public string AdmissionType { get; set; }
    }
}
