//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;

    public partial class qryReport1StudentNew
    {
 
        public Nullable<System.DateTime> FeeReceiptDate { get; set; }
        public string FeeStudentName { get; set; }
        public Nullable<int> FeeStudentID { get; set; }
        public decimal MiscFees { get; set; }
        public decimal MiscFeesMarathi { get; set; }
        public Nullable<decimal> FirstHalf { get; set; }
        public Nullable<decimal> SecondHalf { get; set; }
        public Nullable<decimal> FullYear { get; set; }
        public decimal TermFee1 { get; set; }
        public decimal TermFee2 { get; set; }
        public Nullable<decimal> TutionFees { get; set; }
        public decimal AdmissionFee { get; set; }
        public Nullable<decimal> MiscCalender { get; set; }
        public Nullable<decimal> MIscICard { get; set; }
        public Nullable<decimal> MiscExamFees { get; set; }
        public Nullable<decimal> MiscVVN { get; set; }
        public Nullable<decimal> MiscComputerFees { get; set; }
        public Nullable<decimal> MiscMiscFees { get; set; }
        public string AcadamicCourceDescription { get; set; }
        public string FeeCourseName { get; set; }
        public string FeeBatchName { get; set; }
        public Nullable<int> FeeReceiptNo { get; set; }
    }
}
