//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class qryReport1StudentNewT
    { 
        public Nullable<System.DateTime> FeeReceiptDate { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        
        public string FeeModeofPay { get; set; } 
        public string FeeStudentName { get; set; }
        public string StudentName { get; set; }
        public string FullName { get; set; } 
        
        public Nullable<int> FeeStudentID { get; set; }
        public Nullable<int> Feeid { get; set; }
        public Nullable<decimal> MiscFees { get; set; }
        public Nullable<decimal> MiscFeesMarathi { get; set; }
        public Nullable<decimal> TermFee1 { get; set; }
        public Nullable<decimal> TermFee2 { get; set; }
        public Nullable<decimal> TutionFees { get; set; }

        public Nullable<decimal> Apr { get; set; }
        public Nullable<decimal> May { get; set; }
        public Nullable<decimal> Jun { get; set; }
        public Nullable<decimal> Jul { get; set; }
        public Nullable<decimal> Aug { get; set; }
        public Nullable<decimal> Sep { get; set; }
        public Nullable<decimal> Oct { get; set; }
        public Nullable<decimal> Nov { get; set; }
        public Nullable<decimal> Dec { get; set; }
        public Nullable<decimal> Jan { get; set; }
        public Nullable<decimal> Feb { get; set; }
        public Nullable<decimal> Mar { get; set; }
        public Nullable<decimal> Bounce { get; set; }
        public Nullable<decimal> Lumsum { get; set; }
        public Nullable<decimal> FirstHalf { get; set; }
        public Nullable<decimal> SecondHalf { get; set; }
        public Nullable<decimal> FullYear { get; set; }
        public Nullable<decimal> Balance2122 { get; set; }
        public Nullable<decimal> Balance2021 { get; set; }
        public Nullable<decimal> Balance1920 { get; set; }
               
        public Nullable<decimal> AdmissionFee { get; set; }
        public Nullable<decimal> MiscCalender { get; set; }
        public Nullable<decimal> MIscICard { get; set; }
        public Nullable<decimal> MiscExamFees { get; set; }
        public Nullable<decimal> MiscVVN { get; set; }
        public Nullable<decimal> MiscComputerFees { get; set; }
        public Nullable<decimal> MiscMiscFees { get; set; }
        public Nullable<decimal> MiscEscortCard { get; set; }
        public string AcadamicCourceDescription { get; set; }
        public Nullable<int>  FeeReceiptNo { get; set; }
        public string FeeCourseName { get; set; }
        public string FeeBatchName { get; set; }
        public string CurrentStandard { get; set; }
        public string CurrentBatch { get; set; }
        public string UserName { get; set; }
        public string AdmissionType { get; set; }
        public string GRType { get; set; }

        public Nullable<DateTime> DateOfLeavingSchool { get; set; }
        public Nullable<DateTime> DateofAdmissionImport { get; set; }


        public string StudentAdmissionType { get; set; }
        public string Medium { get; set; }
    }
}
