//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryStudentNew
    {
        public Nullable<System.DateTime> StudentDOB { get; set; }
        public string StudentBirthPlace { get; set; }
        public string StudentMotherTongue { get; set; }
        public string StudentCategory { get; set; }
        public string StudentReligion { get; set; }
        public string StudentCaste { get; set; }
        public string StudentState { get; set; }
        public string StudentCountry { get; set; }
        public string StudentMotherName { get; set; }
        public string StudentAadharNumber { get; set; }
        public string StudentPreviousSchoolName { get; set; }
        public string StudentPreviousSchoolDetails { get; set; }
        public string StudentPreviousQualification { get; set; }
        public string StudentLCNo { get; set; }
        public string UIDAdharCardNo { get; set; }
        public string GeneralRegisterNO { get; set; }
        public string StudentSubCaste { get; set; }
        public string StudentTaluka { get; set; }
        public string StudentDistrict { get; set; }
        public string SchoolUDISENo { get; set; }
        public Nullable<System.DateTime> DateOfLeavingSchool { get; set; }
        public string DateOfBirthinwords { get; set; }
        public string StudentProgress { get; set; }
        public string StudentConduct { get; set; }
        public string StandardInWhichStudyingFigure { get; set; }
        public string StandardInWhichStudyingWord { get; set; }
        public string ReasonForLeavingSchool { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> StudentAdmissionDates { get; set; }
        public string StudentStandard { get; set; }
        public string StandardInWhichStudyingSinceWhenFigure { get; set; }
        public string StandardInWhichStudyingSinceWhenWord { get; set; }
        public string StudentSARALID { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateofAdmissionImport { get; set; }
        public string StandardDivisionImport { get; set; }
        public string UserName { get; set; }
        public string Id { get; set; }
        public string Photo { get; set; }
    }
}
