//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryStudentAdmissionAY25
    {
        public string Id { get; set; }
        public string UserName { get; set; }
        public string UserType { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentMiddleName { get; set; }
        public string StudentLastName { get; set; }
        public Nullable<System.DateTime> StudentDOB { get; set; }
        public string StudentBirthPlace { get; set; }
        public string StudentGender { get; set; }
        public string StudentBloodGroup { get; set; }
        public string StudentNationality { get; set; }
        public string StudentMotherTongue { get; set; }
        public string StudentCategory { get; set; }
        public string StudentReligion { get; set; }
        public string StudentCaste { get; set; }
        public string StudentAddress { get; set; }
        public string StudentLocality { get; set; }
        public string StudentPincode { get; set; }
        public string StudentCity { get; set; }
        public string StudentState { get; set; }
        public string StudentCountry { get; set; }
        public string StudentPhone { get; set; }
        public string StudentParentMobile { get; set; }
        public string StudentParentEmail { get; set; }
        public string StudentParentName { get; set; }
        public string StudentParentPhone { get; set; }
        public string StudentParentAddress { get; set; }
        public string StudentParentLocality { get; set; }
        public string StudentParentPincode { get; set; }
        public string StudentParentCity { get; set; }
        public string StudentParentState { get; set; }
        public string StudentParentCountry { get; set; }
        public string StudentParentRelation { get; set; }
        public string StudentParentEducation { get; set; }
        public string StudentParentOccupation { get; set; }
        public string StudentParentIncome { get; set; }
        public string StudentParentFamilyIncome { get; set; }
        public string StudentFatherName { get; set; }
        public string StudentFatherMobile { get; set; }
        public string StudentFatherJob { get; set; }
        public string StudentMotherName { get; set; }
        public string StudentMotherMobile { get; set; }
        public string StudentMotherJob { get; set; }
        public string StudentAadharNumber { get; set; }
        public int StudentAdmissionId { get; set; }
        public Nullable<int> StudentAdmissionNo { get; set; }
        public Nullable<System.DateTime> StudentAdmissionDate { get; set; }
        public string StudenntCourse { get; set; }
        public string StudentBatch { get; set; }
        public string StudentWeight { get; set; }
        public string StudentHeight { get; set; }
        public string StudentHealth { get; set; }
        public string StudentPhoto { get; set; }
        public string StudentInstitution { get; set; }
        public string StudentRollNo { get; set; }
        public string StudentRouteCode { get; set; }
        public string StudentDestination { get; set; }
        public Nullable<System.DateTime> StudentStartDate { get; set; }
        public Nullable<System.DateTime> StudentEndDate { get; set; }
        public string StudentPreviousSchoolName { get; set; }
        public string StudentPreviousSchoolDetails { get; set; }
        public string StudentPreviousQualification { get; set; }
        public string StudentFeeCategory { get; set; }
        public string StudentAcadamicYear { get; set; }
        public string AspNetUserID { get; set; }
        public string Name { get; set; }
        public string RollName { get; set; }
        public string UName { get; set; }
        public string UNameD { get; set; }
        public Nullable<System.DateTime> StudentBatchStartDate { get; set; }
        public Nullable<System.DateTime> StudentBatchEndDate { get; set; }
        public string StudentLCNo { get; set; }
        public string StudentAdmissionNoGR { get; set; }
        public string UIDAdharCardNo { get; set; }
        public string GeneralRegisterNO { get; set; }
        public string StudentSubCaste { get; set; }
        public string StudentTaluka { get; set; }
        public string StudentDistrict { get; set; }
        public string DateOfBirthinwords { get; set; }
        public string SchoolUDISENo { get; set; }
        public string StudentProgress { get; set; }
        public string StudentConduct { get; set; }
        public Nullable<System.DateTime> DateOfLeavingSchool { get; set; }
        public string StandardInWhichStudyingFigure { get; set; }
        public string StandardInWhichStudyingWord { get; set; }
        public string ReasonForLeavingSchool { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> StudentAdmissionDates { get; set; }
        public string StudentStandard { get; set; }
        public string StandardInWhichStudyingSinceWhenFigure { get; set; }
        public string StandardInWhichStudyingSinceWhenWord { get; set; }
        public string StudentSARALID { get; set; }
        public string StudentName { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> DateofAdmissionImport { get; set; }
        public string StandardDivisionImport { get; set; }
        public string GRType { get; set; }
        public string AdmissionFormPhoto { get; set; }
        public string BirthLeavingCertificatePhoto { get; set; }
        public string CasteCertificatePhoto { get; set; }
        public string AdharCardPhoto { get; set; }
        public string FirstGuardianEmail { get; set; }
        public string SecondGuardianEmail { get; set; }
        public string FirstGuardianMobile { get; set; }
        public string SecondGuardianMobile { get; set; }
        public string ImportDate { get; set; }
        public Nullable<int> Feeid { get; set; }
        public string AdmissionType { get; set; }
        public string Medium { get; set; }
        public string CurrentStandard { get; set; }
        public string CurrentBatch { get; set; }
        public string AcadamicYear { get; set; }
        public string ToBeDelete { get; set; }
        public string FullName { get; set; }
        public string FeeDues { get; set; }
    }
}
