//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class qryTaskView
    {
        public string TaskPriority { get; set; }
        public Nullable<System.DateTime> TaskDueOn { get; set; }
        public string TaskDueOnTime { get; set; }
        public string TaskStatus { get; set; }
        public string Expr1 { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string LastUpdatedUser { get; set; }
        public int Taskid { get; set; }
        public string TaskTo { get; set; }
        public string TaskFrom { get; set; }
        public string TaskToEmail { get; set; }
        public string TaskFromEmail { get; set; }
        public string UserName { get; set; }
        public string PartyName { get; set; }
        public string ProductName { get; set; }
        public string Country { get; set; }
        public string TypeofWork { get; set; }
        public string Depatment { get; set; }
        public string TaskCC { get; set; }
        public Nullable<System.DateTime> TaskDateTime { get; set; }
    }
}
