//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDT
    {        [Key]
        public int TaskDTid { get; set; }
        public Nullable<int> Taskid { get; set; }
        public string TaskPriority { get; set; }
        public Nullable<System.DateTime> TaskDueOn { get; set; }
        public string TaskDueOnTime { get; set; }
        public string TaskStatus { get; set; }
        public string TaskDetails { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string LastUpdatedUser { get; set; }
        public string TaskRead { get; set; }
        public string TaskReadBy { get; set; }
        public string TaskTo { get; set; }
        public string TaskFrom { get; set; }
        public string AcadamicYear { get; set; }
    }
}
