//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskM()
        {
            this.TaskDTMs = new HashSet<TaskDTM>();
        }
    
        public int Taskid { get; set; }
        public string TaskDetails { get; set; }
        public string TaskTo { get; set; }
        public string TaskFrom { get; set; }
        public string TaskToEmail { get; set; }
        public string TaskFromEmail { get; set; }
        public string UserName { get; set; }
        public string PartyName { get; set; }
        public string ProductName { get; set; }
        public string Country { get; set; }
        public string TypeofWork { get; set; }
        public string Depatment { get; set; }
        public string TaskCC { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public Nullable<System.DateTime> TaskDateTime { get; set; }
        public string TaskPriority { get; set; }
        public string TaskStatus { get; set; }
        public Nullable<System.DateTime> TaskDueOn { get; set; }
        public string TaskDueOnTime { get; set; }
        public Nullable<System.TimeSpan> TaskTime { get; set; }
        public string GroupTask { get; set; }
        public string CustomerType { get; set; }
        public string AcadamicYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDTM> TaskDTMs { get; set; }
    }
}
