//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tblAcadamicCertificate
    {
        [Key]
        public int AcadamicCertificateID { get; set; }
        public string SchoolName { get; set; }
        public string AwardedTo { get; set; }
        public string AwardedID { get; set; }
        public string AwardedClass { get; set; }
        public string AwardedFor { get; set; }
        public string AwardedSession { get; set; }
        public Nullable<System.DateTime> AwardedDated { get; set; }
        public string AwardedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string AcadamicYear { get; set; }
    }
}
