//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblAcadamicYear
    {

        [Key]
        public int AcadamicYearId { get; set; }
        public string AcadamicStartYear { get; set; }
        public string AcadamicStartMonth { get; set; }
        public string AcadamicEndYear { get; set; }
        public string AcadamicEndMonth { get; set; }
        public string AcadamicStatus { get; set; }
        public string AcadamicYear { get; set; }
    }
}
