//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblAcadamicCource
    {
        [Key]        
        public int AcadamicCourceId { get; set; }
        public string AcadamicCourceName { get; set; }
        public string AcadamicCourceDescription { get; set; }
        public string AcadamicCourceCode { get; set; }
        public Nullable<int> AcadamicCourceMinAttn { get; set; }
        public string AcadamicCourceAttnType { get; set; }
        public Nullable<int> AcadamicCourceTotalWorkingDays { get; set; }
        public string AcadamicCourceSyllabus { get; set; }
        public string AcadamicYear { get; set; }
        public string CourseStream { get; set; }
    }
}
