//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblAssignmentNote
    {
        [Key]
        public int AssignmentNotesId { get; set; }
        public string AssignTitleNotes { get; set; }
        public string AssignDescriptionNotes { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
        public string Subject { get; set; }
        public string DateofSubmission { get; set; }
        public string NotesUpload { get; set; }
        public string YoutubeLink { get; set; }
        public string AcadamicYear { get; set; }
    }
}
