//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAutoIncrement
    {
        public int AutoIncrementID { get; set; }
        public Nullable<int> lessonPlanningId { get; set; }
        public Nullable<int> FeePaymentId { get; set; }
        public Nullable<int> FeeReceiptNo { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
        public Nullable<int> RegisterNumber { get; set; }
        public string AcadamicYear { get; set; }
        public Nullable<int> RollNumber { get; set; }
        public Nullable<int> EmployeeCode { get; set; }
    }
}
