//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBookRequest
    {
                [Key]
        public int BookRequestId { get; set; }
        public string BookRequestUserType { get; set; }
        public string BookRequestUser { get; set; }
        public string BookRequestBookNo { get; set; }
        public string BookRequestTitle { get; set; }
        public Nullable<System.DateTime> BookRequestDate { get; set; }
        public string BookRequestStatus { get; set; }
        public string AcadamicYear { get; set; }
    }
}
