//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCircular
    {
                [Key]
        public int CircularId { get; set; }
        public string CircularSubject { get; set; }
        public string CircularRefNo { get; set; }
        public string CircularContents { get; set; }
        public Nullable<System.DateTime> CircularDate { get; set; }
        public string PublishToDepartment { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
        public string Subject { get; set; }
        public string PublishToAll { get; set; }
        public string AcadamicYear { get; set; }
    }
}
