//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConversation
    {
                [Key]
        public int ID { get; set; }
        public string Conv { get; set; }
        public string ConvBy { get; set; }
        public string ConvTo { get; set; }
        public Nullable<System.DateTime> ConvDate { get; set; }
        public string ClassName { get; set; }
        public string BatchName { get; set; }
        public string Department { get; set; }
        public string AcadamicYear { get; set; }
        public string IsReceived { get; set; }
        public string NotificationType { get; set; }
        public string AvailableStatus { get; set; }
        public string MessageType { get; set; }
        public Nullable<int> ConvId { get; set; }
    }
}
