//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCourseBatch
    {
                [Key]
        public int BatchId { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
        public Nullable<System.DateTime> BatchStartDate { get; set; }
        public Nullable<System.DateTime> BatchEndDate { get; set; }
        public Nullable<int> MaximumStudent { get; set; }
        public string Active { get; set; }
        public string AcadamicYear { get; set; }
    }
}
