//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeSalaryDT
    {
                [Key]
        public int EmployeeSalaryDTId { get; set; }
        public Nullable<int> EmployeeSalaryId { get; set; }
        public string PayHead { get; set; }
        public Nullable<decimal> PayHeadAmount { get; set; }
        public string AcadamicYear { get; set; }
    }
}
