//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;

    public partial class tblExamMarkObtained
    {
        [Key]
        public int MarkObtainedID { get; set; }
        public string ExamName { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
        public string StudentID { get; set; }
        public string StudentUserName { get; set; }
        public string SubjectName { get; set; }
        public Nullable<int> SubjectMarksTheory { get; set; }
        public Nullable<int> SubjectMarksTheoryObtained { get; set; }
        public Nullable<int> SubjectMarksPractice { get; set; }
        public Nullable<int> SubjectMarksPracticeObtained { get; set; }
        public Nullable<int> SubjectMarksTotal { get; set; }
        public Nullable<int> SubjectMarksTotalObtained { get; set; }
        public Nullable<int> StudentRollNumber { get; set; }
        public string StudentName { get; set; }
        public string AcadamicYear { get; set; }
        public Nullable<int> FormationDaytoDayObservation { get; set; }
        public Nullable<int> FormationDaytoDayObservationObtained { get; set; }
        public Nullable<int> FormationOralwork { get; set; }
        public Nullable<int> FormationOralworkObtained { get; set; }
        public Nullable<int> FormationPracticalExperiment { get; set; }
        public Nullable<int> FormationPracticalExperimentObtained { get; set; }
        public Nullable<int> FormationActivity { get; set; }
        public Nullable<int> FormationActivityObtained { get; set; }
        public Nullable<int> FormationProject { get; set; }
        public Nullable<int> FormationProjectObtained { get; set; }
        public Nullable<int> FormationTestOpenBook { get; set; }
        public Nullable<int> FormationTestOpenBookObtained { get; set; }
        public Nullable<int> FormationHomeClasswork { get; set; }
        public Nullable<int> FormationHomeClassworkObtained { get; set; }
        public Nullable<int> FormationOthers { get; set; }
        public Nullable<int> FormationOthersObtained { get; set; }
        public Nullable<int> FormationTotalA { get; set; }
        public Nullable<int> FormationTotalAObtained { get; set; }
        public Nullable<int> SummativeTheory { get; set; }
        public Nullable<int> SummativeTheoryObtained { get; set; }
        public Nullable<int> SummativeOralPractical { get; set; }
        public Nullable<int> SummativeOralPracticalObtained { get; set; }
        public Nullable<int> SummativeTotalB { get; set; }
        public Nullable<int> SummativeTotalBObtained { get; set; }
    }
}
