//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExamHall
    {
        public int ExamHallId { get; set; }
        public Nullable<int> HallNo { get; set; }
        public Nullable<int> NoofSeats { get; set; }
        public string AcadamicYear { get; set; }
    }
}
