//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeSalaryHD
    {
                [Key]
        public int EmployeeSalaryId { get; set; }
        public string EmpDesignation { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> EmpYear { get; set; }
        public string EmpMonth { get; set; }
        public Nullable<System.DateTime> EmpStartDate { get; set; }
        public Nullable<System.DateTime> EmpEndDate { get; set; }
        public Nullable<System.DateTime> SalaryProcessedDate { get; set; }
        public string AcadamicYear { get; set; }
    }
}
