//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeWaiver
    {        [Key]
        public int FeeWaiverId { get; set; }
        public string FeeCategoryName { get; set; }
        public string FeeSubCategoryName { get; set; }
        public string FeeExcemption { get; set; }
        public string FeeExcemptionCategory { get; set; }
        public string FeeExcemptionGender { get; set; }
        public Nullable<decimal> FeeExcemptionDeduction { get; set; }
        public string AcadamicYear { get; set; }
    }
}
