//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeSubCategoryFine
    {
        public int FeeSubCategoryFineId { get; set; }
        public string FeeCategoryName { get; set; }
        public string FeeSubCategoryName { get; set; }
        public string FeeFineMode { get; set; }
        public Nullable<decimal> FeeFineAmount { get; set; }
        public Nullable<double> FeeFinePercentage { get; set; }
        public string FeeFineType { get; set; }
        public string FineReason { get; set; }
        public string AcadamicYear { get; set; }
    }
}
