//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeAllocation
    {
        public int FeeAllocationId { get; set; }
        public string FeeCategoryName { get; set; }
        public string FeeSubCategoryName { get; set; }
        public Nullable<decimal> FeeAmount { get; set; }
        public string FeeForCourse { get; set; }
        public string FeeForBatch { get; set; }
        public string FeeForStudent { get; set; }
        public Nullable<int> FeeForStudentID { get; set; }
        public string AcadamicYear { get; set; }
    }
}
