//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryIssueDtl
    {
                [Key]
        public int InventoryIssueDtlID { get; set; }
        public Nullable<int> InventoryIssueID { get; set; }
        public string InventoryCategory { get; set; }
        public string InventoryItem { get; set; }
        public Nullable<int> InventoryQty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
        public Nullable<int> InventoryItemId { get; set; }
        public string AcadamicYear { get; set; }
    
        public virtual tblInventoryIssue tblInventoryIssue { get; set; }
    }
}
