//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInventoryIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblInventoryIssue()
        {
            this.tblInventoryIssueDtls = new HashSet<tblInventoryIssueDtl>();
        }
            [Key]
        public int InventoryIssueID { get; set; }
        public string UserType { get; set; }
        public string UserName { get; set; }
        public string UserID { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> ReceiptNo { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string AcadamicYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblInventoryIssueDtl> tblInventoryIssueDtls { get; set; }
    }
}
