//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLessonPlanning
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblLessonPlanning()
        {
            this.tblLessonPlanningDTs = new HashSet<tblLessonPlanningDT>();
        }
    
        public int LessonPlanningId { get; set; }
        public Nullable<int> LessonPlanningCourseID { get; set; }
        public string LessonPlanningCourseName { get; set; }
        public Nullable<int> LessonPlanningBatchID { get; set; }
        public string LessonPlanningBatchName { get; set; }
        public string LessonPlanningSubject { get; set; }
        public string AcadamicYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLessonPlanningDT> tblLessonPlanningDTs { get; set; }
    }
}
