//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLessonPlanningDT
    {        [Key]
        public int LessonPlanningDTId { get; set; }
        public Nullable<int> LessonPlanningId { get; set; }
        public string LessonPlanningLectureCode { get; set; }
        public string LessonPlanningLectureTopic { get; set; }
        public string LessonPlanningSubjectdt { get; set; }
        public string AcadamicYear { get; set; }
    
        public virtual tblLessonPlanning tblLessonPlanning { get; set; }
    }
}
