//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveApplication
    {        [Key]
        public int LeaveApplicationId { get; set; }
        public Nullable<System.DateTime> LeaveFromDate { get; set; }
        public Nullable<System.DateTime> LeaveToDate { get; set; }
        public string LeaveReason { get; set; }
        public string LeaveStatus { get; set; }
        public string ApplyForOnDuty { get; set; }
        public string LeaveCategory { get; set; }
        public Nullable<double> LeaveCount { get; set; }
        public string EmpID { get; set; }
        public string EmpName { get; set; }
        public string EmpDesignation { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string AcadamicYear { get; set; }
    }
}
