//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLeaveDetail
    {        [Key]
        public int LeaveDetailsId { get; set; }
        public string LeaveCategory { get; set; }
        public string EmpDesignation { get; set; }
        public Nullable<decimal> LeaveCount { get; set; }
        public string AcadamicYear { get; set; }
    }
}
