//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOnlinePayment
    {        [Key]
        public int OnlineID { get; set; }
        public string TrackingID { get; set; }
        public string Orderid { get; set; }
        public string SessionID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UserID { get; set; }
        public string Status { get; set; }
        public string BankReferenceNo { get; set; }
        public Nullable<int> FeeDescID { get; set; }
    }
}
