//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseOrderDT
    {
        public int PurchaseOrderDTID { get; set; }
        public Nullable<int> PurcahseOrderId { get; set; }
        public string PurchaseOrderItemCode { get; set; }
        public string PurchaseOrderItemName { get; set; }
        public Nullable<decimal> PurchaseOrderItemRate { get; set; }
        public Nullable<decimal> POItemMRP { get; set; }
        public Nullable<int> POItemQty { get; set; }
        public Nullable<decimal> POItemDiscount { get; set; }
        public Nullable<int> POItemFree { get; set; }
        public Nullable<decimal> POItemNetAmount { get; set; }
        public Nullable<decimal> POItemCGST { get; set; }
        public Nullable<decimal> POItemSGST { get; set; }
        public Nullable<decimal> POItemIGST { get; set; }
        public Nullable<decimal> POItemTotalAmount { get; set; }
        public string ItemCategory { get; set; }
        public string AcadamicYear { get; set; }
    
        public virtual tblPurchaseOrder tblPurchaseOrder { get; set; }
    }
}
