//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPurchaseReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPurchaseReceipt()
        {
            this.tblStockInventoryItems = new HashSet<tblStockInventoryItem>();
        }
    
        public int PurchaseReceiptId { get; set; }
        public string PurchaseInvoiceNo { get; set; }
        public string PurchaseVendor { get; set; }
        public Nullable<int> PurchaseVendorID { get; set; }
        public Nullable<int> PurchaseOrderNo { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string PaidStatus { get; set; }
        public string PaymentRemark { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public string LastModifiedby { get; set; }
        public Nullable<System.DateTime> LastModifiedDateTime { get; set; }
        public string AcadamicYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStockInventoryItem> tblStockInventoryItems { get; set; }
    }
}
