//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentAttendance
    {
        public int AttendanceStudentID { get; set; }
        public string CourseName { get; set; }
        public string BatchName { get; set; }
        public string StudentID { get; set; }
        public string StudentUserName { get; set; }
        public Nullable<int> StudentRollNumber { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public string AttendanceTimeIn { get; set; }
        public string AttendanceRemark { get; set; }
        public string AttendanceTimeOut { get; set; }
        public Nullable<System.DateTime> LastmodifiedDate { get; set; }
        public string LastmodifiedBy { get; set; }
        public string AttendanceStatus { get; set; }
        public string SubjectName { get; set; }
        public string StudentPhoto { get; set; }
        public string AcadamicYear { get; set; }
    }
}
