//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockIssue
    {        [Key]
        public int StockIssueId { get; set; }
        public string StockIssueUser { get; set; }
        public Nullable<int> EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentName { get; set; }
        public string ItemCategory { get; set; }
        public string InventoryItem { get; set; }
        public Nullable<int> InventoryQuantityIssue { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public string IssueReceiptNo { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string AcadamicYear { get; set; }
    }
}
