//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStoreVendor
    {
        public int VendorId { get; set; }
        public string VendorCompany { get; set; }
        public string VendorCompanyPhone { get; set; }
        public string VendorCompanyMobile { get; set; }
        public string VendorCompanyEmail { get; set; }
        public string VendorCompanyCountry { get; set; }
        public string VendorCompanyState { get; set; }
        public string VendorCompanyCity { get; set; }
        public string VendorCompanyLocality { get; set; }
        public string VendorCompanyAddress { get; set; }
        public string VendorContactPerson { get; set; }
        public string VendorServiceProduct { get; set; }
        public string VendorBankName { get; set; }
        public string VendorBranchName { get; set; }
        public string VendorAccountNumber { get; set; }
        public string VendorIFSCCode { get; set; }
        public string VendorCategory { get; set; }
        public string AcadamicYear { get; set; }
    }
}
