//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentAdmissionAY25
    {        [Key]
        public int StudentAdmissionId { get; set; }
        public Nullable<int> StudentAdmissionNo { get; set; }
        public Nullable<System.DateTime> StudentAdmissionDate { get; set; }
        public string StudenntCourse { get; set; }
        public string StudentBatch { get; set; }
        public string StudentWeight { get; set; }
        public string StudentHeight { get; set; }
        public string StudentHealth { get; set; }
        public string StudentPhoto { get; set; }
        public string StudentInstitution { get; set; }
        public string StudentRollNo { get; set; }
        public string StudentRouteCode { get; set; }
        public string StudentDestination { get; set; }
        public Nullable<System.DateTime> StudentStartDate { get; set; }
        public Nullable<System.DateTime> StudentEndDate { get; set; }
        public string StudentFeeCategory { get; set; }
        public string StudentAcadamicYear { get; set; }
        public string AspNetUserID { get; set; }
        public string StudentSubjects { get; set; }
        public Nullable<int> StudentLastIDLink { get; set; }
        public string AcadamicYear { get; set; }
        public Nullable<System.DateTime> StudentBatchStartDate { get; set; }
        public Nullable<System.DateTime> StudentBatchEndDate { get; set; }
        public string StudentSteam { get; set; }
        public string CurrentStandard { get; set; }
        public string CurrentBatch { get; set; }
        public string FirstGuardianEmail { get; set; }
        public string SecondGuardianEmail { get; set; }
        public string FirstGuardianMobile { get; set; }
        public string SecondGuardianMobile { get; set; }
        public Nullable<System.DateTime> LastUpdatedDateTime { get; set; }
        public string LastUpdatedBy { get; set; }
        public string AdmissionType { get; set; }
        public string Medium { get; set; }
        public string ToBeDelete { get; set; }
        public string Updated { get; set; }
        public string FeeDues { get; set; }
    }
}
