//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentGatePass
    {
        public int StudentGatePassId { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string PersonName { get; set; }
        public string PersonContact { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string VisitReason { get; set; }
        public string VisitAuthorisedBy { get; set; }
        public string AcadamicYear { get; set; }
    }
}
