//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportAllocation
    {        [Key]
        public int TransportAllocationId { get; set; }
        public string TransportRoute { get; set; }
        public string TransportDestination { get; set; }
        public string TransportPassengerType { get; set; }
        public string TransportStudentCourse { get; set; }
        public string TransportStudentBatch { get; set; }
        public string TransportStudentName { get; set; }
        public Nullable<int> TransportStudentID { get; set; }
        public Nullable<System.DateTime> TransportStartFequency { get; set; }
        public Nullable<System.DateTime> TransportEndFrequency { get; set; }
        public string AcadamicYear { get; set; }
    }
}
