//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransportVehicle
    {        [Key]
        public int VehicleId { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<int> VehicleSeats { get; set; }
        public Nullable<int> MaximumAllowed { get; set; }
        public string VehicleType { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<System.DateTime> InsuranceRenewDate { get; set; }
        public string TrackID { get; set; }
        public string AcadamicYear { get; set; }
    }
}
