//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Core.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTimeTableHD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTimeTableHD()
        {
            this.tblTimeTableDTs = new HashSet<tblTimeTableDT>();
        }
    
        public int TimeTableId { get; set; }
        public string TTCourseName { get; set; }
        public Nullable<int> TTCourseId { get; set; }
        public string TTBatchName { get; set; }
        public Nullable<int> TTBatchId { get; set; }
        public string TimeTableName { get; set; }
        public string TimeTableStatus { get; set; }
        public string AcadamicYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTimeTableDT> tblTimeTableDTs { get; set; }
    }
}
